//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimoIntento.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Facturacion = new HashSet<Facturacion>();
        }

        public int IdCliente { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [StringLength(20, ErrorMessage = "No Más de 20 Caracteres")]
        public string Nombre_Comercial { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [RegularExpression("\\d+$", ErrorMessage = "Este Campo Solo Recibe Números")]
        public string Cedula { get; set; }
        public Nullable<bool> Estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion> Facturacion { get; set; }
        
    }
}
