//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimoIntento.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Condiciones_Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Condiciones_Pagos()
        {
            this.Facturacion = new HashSet<Facturacion>();
        }
    
        public int IdCondicion { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [StringLength(20, ErrorMessage = "No Más de 20 Caracteres")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [RegularExpression("^\\d*", ErrorMessage = "Este Campo Solo Recibe Números")]
        [Range(1, int.MaxValue, ErrorMessage = "El valor debe ser mayor que cero")]
        public Nullable<int> Cantidad_Dias { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion> Facturacion { get; set; }
    }
}
