//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimoIntento.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Facturacion
    {
        public int IdFacuracion { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [StringLength(20, ErrorMessage = "No Más de 20 Caracteres")]
        public string Forma_Pago { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [StringLength(20, ErrorMessage = "No Más de 20 Caracteres")]
        public string Comentario { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [RegularExpression("^\\d*", ErrorMessage = "Este Campo Solo Recibe Números")]
        [Range(1, int.MaxValue, ErrorMessage = "El valor debe ser mayor que cero")]
        public Nullable<int> Cantidad { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        [RegularExpression("^\\d*", ErrorMessage = "Este Campo Solo Recibe Números")]
        [Range(1, int.MaxValue, ErrorMessage = "El valor debe ser mayor que cero")]
        public Nullable<int> Precio_Unitario { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdCondicion { get; set; }
        public Nullable<int> IdVendedor { get; set; }
    
        public virtual Articulos_Facturables Articulos_Facturables { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Condiciones_Pagos Condiciones_Pagos { get; set; }
        public virtual Vendedores Vendedores { get; set; }
    }
}
